---
cidr_networks:
  container: 172.29.220.0/22
  tunnel: 172.29.224.0/22
  storage: 172.29.228.0/22

used_ips:
  - "172.29.220.1"
  - "172.29.224.1"
  - "172.29.228.1"
  - "172.29.232.1"


global_overrides:
  # The internal and external VIP should be different IPs, however they
  # do not need to be on separate networks.
  external_lb_vip_address: 172.29.220.100
  internal_lb_vip_address: "{{ bootstrap_host_public_address | default(ansible_facts['default_ipv4']['address']) }}"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
    - network:
        container_bridge: "br-external"
        container_type: "veth"
        container_interface: "eth12"
        type: "flat"
        net_name: "external"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute


x-infra-hosts: &x-infra-hosts
  infra1:
    ip: 172.29.220.10
x-compute-hosts: &x-compute-hosts
  compute1:
    ip: 172.29.220.20
  compute2:
    ip: 172.29.220.21
x-storage-hosts: &x-storage-hosts
  storage1:
    ip: 172.29.220.30
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "172.29.228.10"

##
## Infrastructure
##
shared-infra_hosts:
  <<: *x-infra-hosts
repo-infra_hosts:
  <<: *x-infra-hosts
haproxy_hosts:
  <<: *x-infra-hosts

##
## OpenStack
##
identity_hosts:
  <<: *x-infra-hosts
storage-infra_hosts:
  <<: *x-infra-hosts
image_hosts:
  <<: *x-infra-hosts
placement-infra_hosts:
  <<: *x-infra-hosts
compute-infra_hosts:
  <<: *x-infra-hosts
orchestration_hosts:
  <<: *x-infra-hosts
dashboard_hosts:
  <<: *x-infra-hosts
network_hosts:
  <<: *x-infra-hosts
compute_hosts:
  <<: *x-compute-hosts
storage_hosts:
  <<: *x-storage-hosts
