---
lxc_hosts_container_build_command: "dnf --assumeyes --installroot=/var/lib/machines/{{ lxc_container_base_name }} install --setopt=install_weak_deps=False --nodocs rootfiles coreutils dnf rocky-release rocky-repos systemd --releasever=8"

lxc_container_map:
  distro: "{{ hostvars[physical_host]['ansible_facts']['distribution'] | lower }}"
  arch: "{{ lxc_architecture_mapping.get( hostvars[physical_host]['ansible_facts']['architecture'] | lower ) }}"
  release: "{{ hostvars[physical_host]['ansible_facts']['distribution_major_version'] }}"
