---
lxc_hosts_container_build_command: "dnf --assumeyes --installroot=/var/lib/machines/{{ lxc_container_base_name }} install --setopt=install_weak_deps=False --nodocs rootfiles coreutils dnf rocky-release rocky-repos --releasever=8"


lxc_container_map:
  distro: rockylinux
  architecture: amd64
  arch: amd64
  release: 8
lxc_cache_map:
  distro: rockylinux
  arch: "{{ lxc_architecture_mapping.get( ansible_facts['architecture'] ) }}"
  release: 8
  copy_from_host:
    - /etc/default/locale
    - /etc/environment
    - /etc/localtime
    - /etc/locale.conf
    - /etc/protocols
    - /etc/pki/rpm-gpg/
    - /etc/yum/pluginconf.d/fastestmirror.conf
    - /etc/yum.repos.d/

lxc_cache_extra_distro_packages:
  - ca-certificates
  - iputils
  - iproute
  - openssh-server
  - policycoreutils
  - procps
  - python3
  - python3-libs
  - rsync              # os_keystone runs serial=1 and uses rsync before the distro packages have been installed on all keystone targets
  - setup
  - sudo
  - systemd
  - systemd-networkd
  - systemd-resolvd
  - systemd-sysv
  - tzdata
