---
# Installs everything on hosts
#
- name: Bootstrap nodes for distributed OSA installation
  hosts: "{{ host | default('infra1,compute1,storage1') }}"
  become: true

  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"

    - name: Loading Variables from OS Common
      import_tasks: tasks/common_vars.yml

  tasks:
    - name: Initialize nodes
      include_tasks: tasks/init-nodes.yml
      args:
        apply:
          tags: 'init'
      tags: init

    - name: Reboot
      include_tasks: tasks/reboot.yml
      tags: reboot

    - name: Setup infra hosts
      include_tasks: tasks/infra-host.yml
      when: tag.find("infra") != -1 # when on an infra tagged host
      tags: infra

    - name: Setup storage hosts
      include_tasks: tasks/storage-host.yml
      when: tag.find("storage") != -1 # when on an infra tagged host
      tags: storage

  post_tasks:
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
