---
- name: Standard System Configuration Variables
  block:
    - name: Loading Variables from OS Common
      include_vars: "{{ item }}"
      with_items:
        - "{{ ansible_distribution }}.yml"

    - name: Check if system is EFI
      stat:
        path: "/sys/firmware/efi"
      register: efi_installed

  always:
    - debug: msg="Variables are now loaded"
...
